name: decoupled
recipe: drupal8

compose:
  - compose.yml

config:
  webroot: web
  via: nginx
  php: '7.1'
  database: mariadb:10.1
  #xdebug: true

tooling:
  build.sh:
    service: appserver
    description: Execute build.sh
    cmd:
      - ./build.sh
  codeception:
    service: appserver
    description: Run codeception
    cmd:
      - ./vendor/bin/codecept

services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

  appserver:
    extras:
      - "apt-get update -y"
      - "apt-get install python-yaml -y"
      #      Rebuild and restart to remove xdebug
      - "rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    overrides:
      services:
        environment:
          WKV_SITE_ENV: lando
          DB_PASS_DRUPAL: drupal8
          DB_USER_DRUPAL: drupal8
          DB_HOST_DRUPAL: database
          DB_NAME_DRUPAL: drupal8
          SITE_URL: 'https://decoupled.lndo.site'

  elasticsearch:
    type: compose
    services:
      image: blacktop/elasticsearch:6.4
      command: /elastic-entrypoint.sh elasticsearch
      ports:
        - "9200:9200"

proxy:
  mailhog:
    - mail.lndo.site
  # Optional. Uncomment the following lines if Elasticsearch is required.
  # elasticsearch:
  #   - elasticsearch.lndo.site:9200

events:
  # Clear caches after a database import
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y
